### ISSUE TITLE
Doubly-drawn creases cause coloring problems

### ISSUE THREAD

**Issue by lahuang4** [alam-shahul/Polygami#12]
As reported by Madonna, some shapes are incorrectly colored (see picture below).

![screenshot_polygami](https://cloud.githubusercontent.com/assets/5505889/25873841/fdc6f950-34dd-11e7-952e-557cf5126fa6.jpg)

This is a result of some rogue doubly-drawn creases. This seems to happen around "concave" corners of a shape -- for example, a C or an O creates this phenomenon. Interestingly, extending the legs of a U causes it to be colored correctly because of the optimized corner placement; however, extending the legs of a C does not similarly optimize corner placement.

![polygami_screenshot_2](https://cloud.githubusercontent.com/assets/5505889/25873977/82b2cbf8-34de-11e7-89cc-ad6f8600ce78.png)

![image](https://cloud.githubusercontent.com/assets/5505889/25874064/e2cf5aec-34de-11e7-9000-1a3f30b8cdd9.png)

**Comment by alam-shahul** [comment]
It's actually not because of the double creasing; rather, its just because the addition of creases stops after a line hits another corner, regardless of which corner it is hitting. The way to fix this would be to ensure that crease formation continues until the line hits a corner of the same priority as the original corner.

**Comment by lahuang4** [comment]
It looks like the culprit is the missing orthogonal valley fold next to the missing chunk of face coloring.

**Comment by alam-shahul** [comment]
Fixed! I basically did what I described in the previous comment.
