### ISSUE TITLE
Labeling mountain/valley creases vs labeling other categories of creases

### ISSUE THREAD

**Issue by alam-shahul** [alam-shahul/Polygami#9]
In Aviv's original version, he reserves the red and blue colors for flat-folding mountain/valley folds. To specify the mountain/valley folds that are not flat-folding but rather raised at 90º angles, he uses orange and green, respectively. He also draws the corner triangles with purple. This is actually very intuitive and practical, and at least for the crease-drawing process, it would be helpful to maintain this practice.

If needed, we can go back after drawing the creases and replace orange with red, and purple and green with blue. However, it might be nice to display this in the final crease pattern for the user's sake. What do you guys think? 

![creases](https://cloud.githubusercontent.com/assets/5505889/24968854/ac840dd8-1f7c-11e7-9c46-70d5c623ef1b.png)

**Comment by lahuang4** [comment]
I personally think the only blue and red crease patterns are more intuitive to a novice user. I had trouble folding these crease patterns yesterday because I didn't know which way the green, orange, and purple creases had to be folded since they were nonstandard; I actually referenced Aviv's original paper to fold them instead of using the colors on the crease pattern.

**Comment by lahuang4** [comment]
We've added "Extended Colors" and "MV Colors" (mountain-valley colors) modes, which the user can switch between.
